// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/delivery/protos/ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         float64                `protobuf:"fixed64,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Budget) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Budget) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         float64                `protobuf:"fixed64,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBudgetRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBudgetRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ListBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*Budget              `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *ListBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

type ReportSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSummaryRequest) Reset() {
	*x = ReportSummaryRequest{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummaryRequest) ProtoMessage() {}

func (x *ReportSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummaryRequest.ProtoReflect.Descriptor instead.
func (*ReportSummaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *ReportSummaryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReportSummaryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ReportSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Totals        map[string]float64     `protobuf:"bytes,1,rep,name=totals,proto3" json:"totals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSummaryResponse) Reset() {
	*x = ReportSummaryResponse{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummaryResponse) ProtoMessage() {}

func (x *ReportSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummaryResponse.ProtoReflect.Descriptor instead.
func (*ReportSummaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *ReportSummaryResponse) GetTotals() map[string]float64 {
	if x != nil {
		return x.Totals
	}
	return nil
}

type BulkImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportError) Reset() {
	*x = BulkImportError{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportError) ProtoMessage() {}

func (x *BulkImportError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportError.ProtoReflect.Descriptor instead.
func (*BulkImportError) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *BulkImportError) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BulkImportError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BulkCreateTransactionsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transactions  []*CreateTransactionRequest `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Workers       uint32                      `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateTransactionsRequest) Reset() {
	*x = BulkCreateTransactionsRequest{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateTransactionsRequest) ProtoMessage() {}

func (x *BulkCreateTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateTransactionsRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *BulkCreateTransactionsRequest) GetTransactions() []*CreateTransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BulkCreateTransactionsRequest) GetWorkers() uint32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type BulkCreateTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      uint32                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Errors        []*BulkImportError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateTransactionsResponse) Reset() {
	*x = BulkCreateTransactionsResponse{}
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateTransactionsResponse) ProtoMessage() {}

func (x *BulkCreateTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateTransactionsResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *BulkCreateTransactionsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *BulkCreateTransactionsResponse) GetRejected() uint32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *BulkCreateTransactionsResponse) GetErrors() []*BulkImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_internal_delivery_protos_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_internal_delivery_protos_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"/internal/delivery/protos/ledger/v1/ledger.proto\x12\tledger.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\":\n" +
	"\x06Budget\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x01R\x05limit\"\xa0\x01\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"G\n" +
	"\x13CreateBudgetRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x01R\x05limit\"V\n" +
	"\x18ListTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.ledger.v1.TransactionR\ftransactions\"B\n" +
	"\x13ListBudgetsResponse\x12+\n" +
	"\abudgets\x18\x01 \x03(\v2\x11.ledger.v1.BudgetR\abudgets\":\n" +
	"\x14ReportSummaryRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\x98\x01\n" +
	"\x15ReportSummaryResponse\x12D\n" +
	"\x06totals\x18\x01 \x03(\v2,.ledger.v1.ReportSummaryResponse.TotalsEntryR\x06totals\x1a9\n" +
	"\vTotalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"=\n" +
	"\x0fBulkImportError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x82\x01\n" +
	"\x1dBulkCreateTransactionsRequest\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.ledger.v1.CreateTransactionRequestR\ftransactions\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\rR\aworkers\"\x8c\x01\n" +
	"\x1eBulkCreateTransactionsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\rR\brejected\x122\n" +
	"\x06errors\x18\x03 \x03(\v2\x1a.ledger.v1.BulkImportErrorR\x06errors2\xf9\x03\n" +
	"\rLedgerService\x12M\n" +
	"\x0eAddTransaction\x12#.ledger.v1.CreateTransactionRequest\x1a\x16.ledger.v1.Transaction\x12O\n" +
	"\x10ListTransactions\x12\x16.google.protobuf.Empty\x1a#.ledger.v1.ListTransactionsResponse\x12>\n" +
	"\tSetBudget\x12\x1e.ledger.v1.CreateBudgetRequest\x1a\x11.ledger.v1.Budget\x12E\n" +
	"\vListBudgets\x12\x16.google.protobuf.Empty\x1a\x1e.ledger.v1.ListBudgetsResponse\x12U\n" +
	"\x10GetReportSummary\x12\x1f.ledger.v1.ReportSummaryRequest\x1a .ledger.v1.ReportSummaryResponse\x12j\n" +
	"\x13BulkAddTransactions\x12(.ledger.v1.BulkCreateTransactionsRequest\x1a).ledger.v1.BulkCreateTransactionsResponseB-Z+internal/delivery/protos/ledger/v1;ledgerv1b\x06proto3"

var (
	file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescData []byte
)

func file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_delivery_protos_ledger_v1_ledger_proto_rawDesc), len(file_internal_delivery_protos_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_internal_delivery_protos_ledger_v1_ledger_proto_rawDescData
}

var file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_delivery_protos_ledger_v1_ledger_proto_goTypes = []any{
	(*Transaction)(nil),                    // 0: ledger.v1.Transaction
	(*Budget)(nil),                         // 1: ledger.v1.Budget
	(*CreateTransactionRequest)(nil),       // 2: ledger.v1.CreateTransactionRequest
	(*CreateBudgetRequest)(nil),            // 3: ledger.v1.CreateBudgetRequest
	(*ListTransactionsResponse)(nil),       // 4: ledger.v1.ListTransactionsResponse
	(*ListBudgetsResponse)(nil),            // 5: ledger.v1.ListBudgetsResponse
	(*ReportSummaryRequest)(nil),           // 6: ledger.v1.ReportSummaryRequest
	(*ReportSummaryResponse)(nil),          // 7: ledger.v1.ReportSummaryResponse
	(*BulkImportError)(nil),                // 8: ledger.v1.BulkImportError
	(*BulkCreateTransactionsRequest)(nil),  // 9: ledger.v1.BulkCreateTransactionsRequest
	(*BulkCreateTransactionsResponse)(nil), // 10: ledger.v1.BulkCreateTransactionsResponse
	nil,                                    // 11: ledger.v1.ReportSummaryResponse.TotalsEntry
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 13: google.protobuf.Empty
}
var file_internal_delivery_protos_ledger_v1_ledger_proto_depIdxs = []int32{
	12, // 0: ledger.v1.Transaction.date:type_name -> google.protobuf.Timestamp
	12, // 1: ledger.v1.CreateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 2: ledger.v1.ListTransactionsResponse.transactions:type_name -> ledger.v1.Transaction
	1,  // 3: ledger.v1.ListBudgetsResponse.budgets:type_name -> ledger.v1.Budget
	11, // 4: ledger.v1.ReportSummaryResponse.totals:type_name -> ledger.v1.ReportSummaryResponse.TotalsEntry
	2,  // 5: ledger.v1.BulkCreateTransactionsRequest.transactions:type_name -> ledger.v1.CreateTransactionRequest
	8,  // 6: ledger.v1.BulkCreateTransactionsResponse.errors:type_name -> ledger.v1.BulkImportError
	2,  // 7: ledger.v1.LedgerService.AddTransaction:input_type -> ledger.v1.CreateTransactionRequest
	13, // 8: ledger.v1.LedgerService.ListTransactions:input_type -> google.protobuf.Empty
	3,  // 9: ledger.v1.LedgerService.SetBudget:input_type -> ledger.v1.CreateBudgetRequest
	13, // 10: ledger.v1.LedgerService.ListBudgets:input_type -> google.protobuf.Empty
	6,  // 11: ledger.v1.LedgerService.GetReportSummary:input_type -> ledger.v1.ReportSummaryRequest
	9,  // 12: ledger.v1.LedgerService.BulkAddTransactions:input_type -> ledger.v1.BulkCreateTransactionsRequest
	0,  // 13: ledger.v1.LedgerService.AddTransaction:output_type -> ledger.v1.Transaction
	4,  // 14: ledger.v1.LedgerService.ListTransactions:output_type -> ledger.v1.ListTransactionsResponse
	1,  // 15: ledger.v1.LedgerService.SetBudget:output_type -> ledger.v1.Budget
	5,  // 16: ledger.v1.LedgerService.ListBudgets:output_type -> ledger.v1.ListBudgetsResponse
	7,  // 17: ledger.v1.LedgerService.GetReportSummary:output_type -> ledger.v1.ReportSummaryResponse
	10, // 18: ledger.v1.LedgerService.BulkAddTransactions:output_type -> ledger.v1.BulkCreateTransactionsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_delivery_protos_ledger_v1_ledger_proto_init() }
func file_internal_delivery_protos_ledger_v1_ledger_proto_init() {
	if File_internal_delivery_protos_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_delivery_protos_ledger_v1_ledger_proto_rawDesc), len(file_internal_delivery_protos_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_protos_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_internal_delivery_protos_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_internal_delivery_protos_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_internal_delivery_protos_ledger_v1_ledger_proto = out.File
	file_internal_delivery_protos_ledger_v1_ledger_proto_goTypes = nil
	file_internal_delivery_protos_ledger_v1_ledger_proto_depIdxs = nil
}
